name: aXe Audit

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and axe_audit
      run: |
        npm install
        npm run axe_audit
      env:
        CI: true
